### ISSUE TITLE
Sample name format guessed incorrectly

### ISSUE THREAD

**Issue by colindaven** [sunbeam-labs/sunbeam#139]
Hi

either this is a bug, or my (almost mint) config files are wrong (how should paths to kraken etc end, eg with a trailing "/" or without ? )

cheers

```
sunbeam run --configfile sunbeam_config_nochanges.yml 
Traceback (most recent call last):
  File "/mnt/ngsnfs/tools/miniconda3/envs/sunbeam/bin/sunbeam", line 11, in <module>
    sys.exit(main())
  File "/mnt/ngsnfs/tools/miniconda3/envs/sunbeam/lib/python3.5/site-packages/sunbeamlib/scripts/command.py", line 38, in main
    Run(remaining)
  File "/mnt/ngsnfs/tools/miniconda3/envs/sunbeam/lib/python3.5/site-packages/sunbeamlib/scripts/run.py", line 38, in main
    cmd = subprocess.run(['snakemake'] + snakemake_args)
  File "/mnt/ngsnfs/tools/miniconda3/envs/sunbeam/lib/python3.5/subprocess.py", line 383, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/mnt/ngsnfs/tools/miniconda3/envs/sunbeam/lib/python3.5/subprocess.py", line 676, in __init__
    restore_signals, start_new_session)
  File "/mnt/ngsnfs/tools/miniconda3/envs/sunbeam/lib/python3.5/subprocess.py", line 1228, in _execute_child
    restore_signals, start_new_session, preexec_fn)
TypeError: Can't convert 'PosixPath' object to str implicitly
```

**Comment by eclarke** [comment]
Could you post your config file contents if possible? It shouldn't matter if they end with a / or not, so this is probably a bug.

**Comment by colindaven** [comment]
Ah, I get this in the tests too

```
tests/run_tests.bash -e sunbeam
Running setup... ✔
Running build_test_data... ✔
Running test_all... 
Failed command error output:
Traceback (most recent call last):
  File "/mnt/ngsnfs/tools/miniconda3/envs/sunbeam/bin/sunbeam", line 11, in <module>
    sys.exit(main())
  File "/mnt/ngsnfs/tools/miniconda3/envs/sunbeam/lib/python3.5/site-packages/sunbeamlib/scripts/command.py", line 38, in main
    Run(remaining)
  File "/mnt/ngsnfs/tools/miniconda3/envs/sunbeam/lib/python3.5/site-packages/sunbeamlib/scripts/run.py", line 38, in main
    cmd = subprocess.run(['snakemake'] + snakemake_args)
  File "/mnt/ngsnfs/tools/miniconda3/envs/sunbeam/lib/python3.5/subprocess.py", line 383, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/mnt/ngsnfs/tools/miniconda3/envs/sunbeam/lib/python3.5/subprocess.py", line 676, in __init__
    restore_signals, start_new_session)
  File "/mnt/ngsnfs/tools/miniconda3/envs/sunbeam/lib/python3.5/subprocess.py", line 1228, in _execute_child
    restore_signals, start_new_session, preexec_fn)
TypeError: Can't convert 'PosixPath' object to str implicitly
x (log: /working2/rcug/scratch/tmp/tmp.Yaa6CjcxBc/test_all.[out/err])
-- TESTS FAILED --
```

config file:
```
# 
# Sunbeam configuration file
#
# Defining samples:
#   Run 'sunbeam list_samples <data_dir>' to create a list of samples and
#   associated fastq.gz files. Samples must be in gzipped fastq format.
#
# Paths:
#   Paths are resolved through the following rules:
#     1. If the path is absolute, the path is parsed as-is
#     2. If the path is not absolute, the path at 'root' is appended to it
#     3. If the path is not 'output_fp', the path is checked to ensure it exists
#
# Suffixes:
#   Each subsection contains a 'suffix' key that defines the folder under
#   'output_fp' where the results of that section are put.
#

# General options
all:
  root: "/mnt/ngsnfs/tools/sunbeam/sunbeam-stable/my_project"
  output_fp: "sunbeam_output"
  samplelist_fp: "samples.csv"
  paired_end: true
  version: "1.2.0"

# Quality control
qc:
  suffix: qc
  # Trimmomatic
  threads: 4
  java_heapsize: 512M
  leading: 3
  trailing: 3
  slidingwindow: [4,15]
  minlen: 36
  adapter_fp: "/mnt/ngsnfs/tools/miniconda3/envs/sunbeam/share/trimmomatic/adapters/NexteraPE-PE.fa"
  # Cutadapt
  fwd_adapters: ['GTTTCCCAGTCACGATC', 'GTTTCCCAGTCACGATCNNNNNNNNNGTTTCCCAGTCACGATC']
  rev_adapters: ['GTTTCCCAGTCACGATC', 'GTTTCCCAGTCACGATCNNNNNNNNNGTTTCCCAGTCACGATC']
  # Komplexity
  kz_threshold: 0.55
  # Decontam.py
  pct_id: 0.5
  frac: 0.6
  host_fp: "/lager2/rcug/seqres/HS/"

# Taxonomic classifications
classify:
  suffix: classify
  threads: 4
  kraken_db_fp: "/lager2/rcug/seqres/metagenref/kraken/minikraken_20171019_8GB/"

# Contig assembly
assembly:
  suffix: assembly
  min_length: 300
  threads: 4

# Contig annotation
annotation:
  suffix: annotation
  min_contig_len: 500
  circular_kmin: 10
  circular_kmax: 1000
  circular_min_len: 3500
  
blast:
  threads: 4

blastdbs:
  root_fp: ""

mapping:
  suffix: mapping
  genomes_fp: "/lager2/rcug/seqres/metagenref/allgenomes_april_2016_complete3.fasta"
  samtools_opts: ""
  threads: 4


```

**Comment by colindaven** [comment]
This is a miniconda3 install on Ubuntu 16.04 if that helps

**Comment by eclarke** [comment]
Weird- sorry about that! Could you try running the following for me and pasting the output here?

From your Sunbeam directory (probably `/mnt/ngsnfs/tools/sunbeam/sunbeam-stable`),  run:
```bash
snakemake --configfile sunbeam_config_nochanges.yml 
```

**Comment by colindaven** [comment]
Thanks, it is probably due to the (admittedly bad) sample naming if I interpret this correctly:


`snakemake --configfile my_project/sunbeam_config_nochanges.yml 

```
`Found extension sbx_test in folder sbx_test
ValueError in line 58 of /mnt/ngsnfs/tools/sunbeam/sunbeam-stable/Snakefile:
Paired-end files specified, but mate pair for '2' is missing or does not exist.
  File "/mnt/ngsnfs/tools/sunbeam/sunbeam-stable/Snakefile", line 58, in <module>
  File "/mnt/ngsnfs/tools/sunbeam/sunbeam-stable/sunbeamlib/__init__.py", line 43, in build_sample_list

```

**Comment by colindaven** [comment]
To be clear, the files are
```
ERR011089_1.fastq.gz
ERR011089_2.fastq.gz
```

and are listed as samples 
```
cat samples.csv 

2,/ngsssd1/rcug/public_metagenome/metahit/ERR011089_2.fastq.gz,
1,/ngsssd1/rcug/public_metagenome/metahit/ERR011089_1.fastq.gz,
```

I'll rename and it should work better.

cheers

**Comment by eclarke** [comment]
@colindaven if you have a moment, could you try installing the dev version of sunbeam and seeing if the error you encountered still persists? You can install the dev version into a new `sunbeam-dev` conda environment like so:
```bash
git clone -b dev https://github.com/sunbeam-labs/sunbeam sunbeam-dev
cd sunbeam-dev
./install.sh -e sunbeam-dev
tests/run_tests.bash -e sunbeam-dev
```

**Comment by colindaven** [comment]
Hi, it seems one test failed on my system:

```
/ngsssd1/rcug/public_metagenome/metahit/sunbeam_dev/sunbeam-dev$ tests/run_tests.bash -e sunbeam-dev
Running setup... ✔
Running build_test_data... ✔
Running test_all... 
Failed command error output:
Found extension sbx_test in folder sbx_test
Collecting host/contaminant genomes... done.
Collecting target genomes... done.
SyntaxError in line 67 of /ngsssd1/rcug/public_metagenome/metahit/sunbeam_dev/sunbeam-dev/rules/reports/reports.rules:
Colon expected after keyword report. (reports.rules, line 67)
  File "/ngsssd1/rcug/public_metagenome/metahit/sunbeam_dev/sunbeam-dev/Snakefile", line 118, in <module>
x (log: /working2/rcug/scratch/tmp/tmp.zk6lVsc3C9/test_all.[out/err])
-- TESTS FAILED --
```

**Comment by eclarke** [comment]
Thanks. It looks like a dependency was updated and that broke a few things. I've locked Sunbeam to the correct version of the dependency for now.

If you don't mind testing this again, you can update using `./install.sh -e sunbeam-dev --update env`. Thanks again for your patience.

**Comment by colindaven** [comment]
No problems. Still no luck, attempted both with an without 
`source activate sunbeam-dev`

Yes, I did remember to 
`./install.sh -e sunbeam-dev --update env`

Strange

```
(sunbeam-dev) rcug@hpc04:/ngsssd1/rcug/public_metagenome/metahit/sunbeam_dev/sunbeam-dev$ tests/run_tests.bash -e sunbeam-dev
Running setup... ✔
Running build_test_data... ✔
Running test_all... 
Failed command error output:
Found extension sbx_test in folder sbx_test
Collecting host/contaminant genomes... done.
Collecting target genomes... done.
SyntaxError in line 67 of /ngsssd1/rcug/public_metagenome/metahit/sunbeam_dev/sunbeam-dev/rules/reports/reports.rules:
Colon expected after keyword report. (reports.rules, line 67)
  File "/ngsssd1/rcug/public_metagenome/metahit/sunbeam_dev/sunbeam-dev/Snakefile", line 118, in <module>
x (log: /working2/rcug/scratch/tmp/tmp.8MM0QTxNUe/test_all.[out/err])
-- TESTS FAILED --
```

**Comment by colindaven** [comment]
This looks a lot more promising !
I'll try the pipeline again later.
```
tests/run_tests.bash -e sunbeam-dev2
Running setup... ✔
Running build_test_data... ✔
Running test_all... ✔
Running test_extensions... ✔
Running test_optional_cutadapt... ✔
Running test_pair_concordance... ✔
Running test_single_end... ✔
Running test_template_option... ✔
Running test_version_check... ✔
-- TESTS SUCCEEDED --

```
