### ISSUE TITLE
Tests failed when installing

### ISSUE THREAD

**Issue by monicawei12** [sunbeam-labs/sunbeam#279]
Hello,
   I managed to install sunbeam successfully with some workaround (added git to the sunbeam conda environment) but now am not passing the tests.  This is the specific error message I get:

tests/run_tests.bash -e sunbeam
Running setup... \u2714
Running build_test_data... \u2714
Running test_all... \u2714
Running test_all_old_illumina... \u2714
Running test_assembly_failures... \u2714
Running test_blank_fp_behavior... \u2714
Running test_extensions... \u2714
Running test_get_paired_unpaired...
Failed command error output:
Traceback (most recent call last):
  File "/home/weimo/anaconda3/envs/sunbeam/lib/python3.6/site-packages/grabseqslib/__init__.py", line 30, in main
    if args.rastid:
AttributeError: 'Namespace' object has no attribute 'rastid'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/weimo/anaconda3/envs/sunbeam/bin/grabseqs", line 11, in <module>
    sys.exit(main())
  File "/home/weimo/anaconda3/envs/sunbeam/lib/python3.6/site-packages/grabseqslib/__init__.py", line 37, in main
    acclist = get_sra_acc_metadata(sra_identifier, args.metadata, args.outdir, args.list, args.no_SRR_parsing)
  File "/home/weimo/anaconda3/envs/sunbeam/lib/python3.6/site-packages/grabseqslib/sra.py", line 47, in get_sra_acc_metadata
    run_col = lines[0].index("Run")
ValueError: 'Run' is not in list
Traceback (most recent call last):
  File "/home/weimo/anaconda3/envs/sunbeam/bin/sunbeam", line 8, in <module>
    sys.exit(main())
  File "/home/weimo/anaconda3/envs/sunbeam/lib/python3.6/site-packages/sunbeamlib/scripts/command.py", line 40, in main
    Init(remaining)
  File "/home/weimo/anaconda3/envs/sunbeam/lib/python3.6/site-packages/sunbeamlib/scripts/init.py", line 21, in main
    samplelists = write_samples_from_input(args, project_fp)
  File "/home/weimo/anaconda3/envs/sunbeam/lib/python3.6/site-packages/sunbeamlib/scripts/init.py", line 115, in write_samples_from_input
    force = args.force)
  File "/home/weimo/anaconda3/envs/sunbeam/lib/python3.6/site-packages/sunbeamlib/scripts/list_samples.py", line 115, in build_sample_list_sra
    samples = find_samples_sra(accessions)
  File "/home/weimo/anaconda3/envs/sunbeam/lib/python3.6/site-packages/sunbeamlib/scripts/list_samples.py", line 170, in find_samples_sra
    result = subprocess.run(cmd_args, stdout=subprocess.PIPE, check=True)
  File "/home/weimo/anaconda3/envs/sunbeam/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['grabseqs', 'sra', '-l', 'ERP020555']' returned non-zero exit status 1.
grep: /tmp/tmp.TIEbQ4hjMx/test_get_paired_unpaired/unpaired_sunbeam_config_SRA.yml: No such file or directory
x (log: /tmp/tmp.TIEbQ4hjMx/test_get_paired_unpaired.[out/err])

Thanks in advance!

**Comment by louiejtaylor** [comment]
Hi @monicawei12, sorry for the very delayed response! This is not an error I've seen before--it looks like the issue is with part of the pipeline that handles downloading external data. The confusing part to me is that you had to explicitly install git; git should be [included the sunbeam environment](https://github.com/sunbeam-labs/sunbeam/blob/dev/environment.yml). That, plus a bunch of errors in a self-contained python dependency make me think that there might have been an issue during the install or environment creation steps.

Did you install from the stable branch or the dev branch? We're planning to release a new stable branch soon as the current one is quite stale. The dev branch was failing the automated testing due to one of the dependencies breaking, but that was fixed today.

If you're still having this issue and are interested in troubleshooting, I do have a suggestion. If you pull in the latest changes `git checkout dev && git pull` and then try a fresh install, updating the environment and library `bash install.sh -u all`. If you get the same error I'll see if I can reproduce your problem.

**Comment by Ulthran** [comment]
Closing this issue as it should be fixed in sunbeam3. If you run into this again please open a new issue.
