### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by sac35** [sunbeam-labs/sunbeam#315]
Hello. During installation, I am getting an error message of:

Error in /home/mayo/sac35/sunbeam-stable/install.sh in function install_env_vars on line 152

**Comment by sac35** [comment]
This is the complete error report:
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/mayo/sac35/miniconda3/lib/python3.9/site-packages/conda/exceptions.py", line 1080, in __call__
        return func(*args, **kwargs)
      File "/home/mayo/sac35/miniconda3/lib/python3.9/site-packages/conda_env/cli/main.py", line 80, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/home/mayo/sac35/miniconda3/lib/python3.9/site-packages/conda_env/cli/main_update.py", line 123, in execute
        result[installer_type] = installer.install(prefix, specs, args, env)
      File "/home/mayo/sac35/miniconda3/lib/python3.9/site-packages/conda_env/installers/conda.py", line 50, in install
        unlink_link_transaction = solver.solve_for_transaction(
      File "/home/mayo/sac35/miniconda3/lib/python3.9/site-packages/conda/core/solve.py", line 114, in solve_for_transaction
        unlink_precs, link_precs = self.solve_for_diff(update_modifier, deps_modifier,
      File "/home/mayo/sac35/miniconda3/lib/python3.9/site-packages/conda/core/solve.py", line 157, in solve_for_diff
        final_precs = self.solve_final_state(update_modifier, deps_modifier, prune, ignore_pinned,
      File "/home/mayo/sac35/miniconda3/lib/python3.9/site-packages/conda/core/solve.py", line 262, in solve_final_state
        ssc = self._collect_all_metadata(ssc)
      File "/home/mayo/sac35/miniconda3/lib/python3.9/site-packages/conda/common/io.py", line 88, in decorated
        return f(*args, **kwds)
      File "/home/mayo/sac35/miniconda3/lib/python3.9/site-packages/conda/core/solve.py", line 425, in _collect_all_metadata
        index, r = self._prepare(prepared_specs)
      File "/home/mayo/sac35/miniconda3/lib/python3.9/site-packages/conda/core/solve.py", line 1020, in _prepare
        reduced_index = get_reduced_index(self.prefix, self.channels,
      File "/home/mayo/sac35/miniconda3/lib/python3.9/site-packages/conda/core/index.py", line 288, in get_reduced_index
        new_records = SubdirData.query_all(spec, channels=channels, subdirs=subdirs,
      File "/home/mayo/sac35/miniconda3/lib/python3.9/site-packages/conda/core/subdir_data.py", line 140, in query_all
        result = tuple(concat(executor.map(subdir_query, channel_urls)))
      File "/home/mayo/sac35/miniconda3/lib/python3.9/concurrent/futures/_base.py", line 608, in result_iterator
        yield fs.pop().result()
      File "/home/mayo/sac35/miniconda3/lib/python3.9/concurrent/futures/_base.py", line 445, in result
        return self.__get_result()
      File "/home/mayo/sac35/miniconda3/lib/python3.9/concurrent/futures/_base.py", line 390, in __get_result
        raise self._exception
      File "/home/mayo/sac35/miniconda3/lib/python3.9/concurrent/futures/thread.py", line 52, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/home/mayo/sac35/miniconda3/lib/python3.9/site-packages/conda/core/subdir_data.py", line 132, in <lambda>
        subdir_query = lambda url: tuple(SubdirData(Channel(url), repodata_fn=repodata_fn).query(
      File "/home/mayo/sac35/miniconda3/lib/python3.9/site-packages/conda/core/subdir_data.py", line 145, in query
        self.load()
      File "/home/mayo/sac35/miniconda3/lib/python3.9/site-packages/conda/core/subdir_data.py", line 210, in load
        _internal_state = self._load()
      File "/home/mayo/sac35/miniconda3/lib/python3.9/site-packages/conda/core/subdir_data.py", line 356, in _load
        _internal_state = self._read_local_repdata(mod_etag_headers.get('_etag'),
      File "/home/mayo/sac35/miniconda3/lib/python3.9/site-packages/conda/core/subdir_data.py", line 442, in _read_local_repdata
        _internal_state = self._process_raw_repodata_str(raw_repodata_str)
      File "/home/mayo/sac35/miniconda3/lib/python3.9/site-packages/conda/core/subdir_data.py", line 480, in _process_raw_repodata_str
        json_obj = json.loads(raw_repodata_str or '{}')
      File "/home/mayo/sac35/miniconda3/lib/python3.9/json/__init__.py", line 346, in loads
        return _default_decoder.decode(s)
      File "/home/mayo/sac35/miniconda3/lib/python3.9/json/decoder.py", line 337, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
      File "/home/mayo/sac35/miniconda3/lib/python3.9/json/decoder.py", line 353, in raw_decode
        obj, end = self.scan_once(s, idx)
    json.decoder.JSONDecodeError: Unterminated string starting at: line 834029 column 9 (char 25165816)

`$ /home/mayo/sac35/miniconda3/bin/conda-env update --name=sunbeam --quiet --file environment.yml`

  environment variables:
                 CIO_TEST=<not set>
  CONDA_AUTO_UPDATE_CONDA=false
               CONDA_ROOT=/home/mayo/sac35/miniconda3
           CURL_CA_BUNDLE=<not set>
        LMOD_PACKAGE_PATH=/usr/share/lmod/lmod/site
                  MANPATH=/usr/share/man:/usr/share/lmod/lmod/share/man:/usr/local/sOGE/sge-8.1.
                          9/man
               MODULEPATH=/usr/local/modules/Modules/dcis:/usr/local/modules/Modules:/etc/module
                          files:/usr/share/modulefiles:/usr/share/lmod/lmod/modulefiles/Core:/us
                          r/local/modulefiles/default:/research/labs/microbiome/chia/apps/module
                          files
                     PATH=/home/mayo/sac35/bin:/usr/local/biotools/bin:/usr/share/lmod/lmod/libe
                          xec:/usr/local/sOGE/sge-8.1.9/bin:/usr/local/sOGE/sge-8.1.9/bin/lx-amd
                          64:/usr/lib64/qt-3.3/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/
                          sbin:/usr/lpp/mmfs/bin:/home/mayo/sac35/miniconda3/bin:/home/mayo/sac3
                          5/miniconda3/bin
           QT_PLUGIN_PATH=/usr/lib64/kde4/plugins:/usr/lib/kde4/plugins
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>
 __LMOD_REF_COUNT_MANPATH=/usr/share/man:2;/usr/share/lmod/lmod/share/man:1;/usr/local/sOGE/sge-
                          8.1.9/man:1
__LMOD_REF_COUNT_MODULEPATH=/usr/local/modules/Modules/dcis:1;/usr/local/modules/Modules:1;/etc/mo
                          dulefiles:1;/usr/share/modulefiles:1;/usr/share/lmod/lmod/modulefiles/
                          Core:1;/usr/local/modulefiles/default:1;/research/labs/microbiome/chia
                          /apps/modulefiles:1
    __LMOD_REF_COUNT_PATH=/usr/share/lmod/lmod/libexec:1;/usr/local/sOGE/sge-8.1.9/bin:1;/usr/lo
                          cal/sOGE/sge-8.1.9/bin/lx-amd64:1;/usr/lib64/qt-3.3/bin:1;/usr/local/b
                          in:2;/usr/bin:1;/usr/local/sbin:1;/usr/sbin:1;/usr/lpp/mmfs/bin:1

     active environment : None
       user config file : /home/mayo/sac35/.condarc
 populated config files : /home/mayo/sac35/.condarc
          conda version : 4.11.0
    conda-build version : not installed
         python version : 3.9.7.final.0
       virtual packages : __cuda=11.4=0
                          __linux=3.10.0=0
                          __glibc=2.17=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /home/mayo/sac35/miniconda3  (writable)
      conda av data dir : /home/mayo/sac35/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/afelten/linux-64
                          https://conda.anaconda.org/afelten/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/mayo/sac35/miniconda3/pkgs
                          /home/mayo/sac35/.conda/pkgs
       envs directories : /home/mayo/sac35/miniconda3/envs
                          /home/mayo/sac35/.conda/envs
               platform : linux-64
             user-agent : conda/4.11.0 requests/2.27.1 CPython/3.9.7 Linux/3.10.0-1160.53.1.el7.x86_64 rhel/7.9 glibc/2.17
                UID:GID : 9349:50107
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
